version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - meda_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - meda_network

networks:
  meda_network:
    driver: bridge
