version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - medbro_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - medbro_network

networks:
  medbro_network:
    driver: bridge
